import type { Match } from "../types.js";
import { teams } from "./teams.js";

export const upcomingFixtures: Match[] = [
  {
    id: "abcdef1",
    slug: "boca-juniors-vs-river-plate",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 9",
    subTournament: "Apertura",
    homeTeam: teams.boca,
    awayTeam: teams.river,
    scheduledDate: "2026-04-18",
    scheduledTime: "20:00",
    status: "scheduled",
    minute: null,
    homeScore: null,
    awayScore: null,
    homeGoalScorers: [],
    awayGoalScorers: [],
    tvNetworks: [{ id: "gchc", name: "ESPN Premium" }],
  },
  {
    id: "abcdef2",
    slug: "racing-club-vs-independiente",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 9",
    subTournament: "Apertura",
    homeTeam: teams.racing,
    awayTeam: teams.independiente,
    scheduledDate: "2026-04-18",
    scheduledTime: "17:00",
    status: "scheduled",
    minute: null,
    homeScore: null,
    awayScore: null,
    homeGoalScorers: [],
    awayGoalScorers: [],
    tvNetworks: [{ id: "idef", name: "TNT Sports Premium" }],
  },
  {
    id: "abcdef3",
    slug: "velez-sarsfield-vs-talleres-de-cordoba",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 9",
    subTournament: "Apertura",
    homeTeam: teams.velez,
    awayTeam: teams.talleres,
    scheduledDate: "2026-04-19",
    scheduledTime: "16:00",
    status: "scheduled",
    minute: null,
    homeScore: null,
    awayScore: null,
    homeGoalScorers: [],
    awayGoalScorers: [],
    tvNetworks: [{ id: "cbcj", name: "TyC Sports" }],
  },
  {
    id: "abcdef4",
    slug: "estudiantes-de-la-plata-vs-san-lorenzo",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 9",
    subTournament: "Apertura",
    homeTeam: teams.estudiantesLP,
    awayTeam: teams.sanLorenzo,
    scheduledDate: "2026-04-19",
    scheduledTime: "18:30",
    status: "scheduled",
    minute: null,
    homeScore: null,
    awayScore: null,
    homeGoalScorers: [],
    awayGoalScorers: [],
    tvNetworks: [{ id: "cicj", name: "ESPN" }],
  },
  {
    id: "abcdef5",
    slug: "lanus-vs-belgrano",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 9",
    subTournament: "Apertura",
    homeTeam: teams.lanus,
    awayTeam: teams.belgrano,
    scheduledDate: "2026-04-19",
    scheduledTime: "20:30",
    status: "scheduled",
    minute: null,
    homeScore: null,
    awayScore: null,
    homeGoalScorers: [],
    awayGoalScorers: [],
    tvNetworks: [{ id: "hbdg", name: "LPF Play" }],
  },
  {
    id: "abcdef6",
    slug: "huracan-vs-barracas-central",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 9",
    subTournament: "Apertura",
    homeTeam: teams.huracan,
    awayTeam: teams.barracas,
    scheduledDate: "2026-04-20",
    scheduledTime: "15:30",
    status: "scheduled",
    minute: null,
    homeScore: null,
    awayScore: null,
    homeGoalScorers: [],
    awayGoalScorers: [],
    tvNetworks: [{ id: "cbcj", name: "TyC Sports" }],
  },
  {
    id: "abcdef7",
    slug: "godoy-cruz-vs-gimnasia-la-plata",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 9",
    subTournament: "Apertura",
    homeTeam: teams.godoyCruz,
    awayTeam: teams.gimnasiaLP,
    scheduledDate: "2026-04-20",
    scheduledTime: "17:00",
    status: "scheduled",
    minute: null,
    homeScore: null,
    awayScore: null,
    homeGoalScorers: [],
    awayGoalScorers: [],
    tvNetworks: [],
  },
  {
    id: "abcdef8",
    slug: "argentinos-juniors-vs-newells-old-boys",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 9",
    subTournament: "Apertura",
    homeTeam: teams.argentinos,
    awayTeam: teams.newells,
    scheduledDate: "2026-04-20",
    scheduledTime: "19:00",
    status: "scheduled",
    minute: null,
    homeScore: null,
    awayScore: null,
    homeGoalScorers: [],
    awayGoalScorers: [],
    tvNetworks: [{ id: "gchc", name: "ESPN Premium" }],
  },
  {
    id: "abcdef9",
    slug: "banfield-vs-defensa-y-justicia",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 10",
    subTournament: "Apertura",
    homeTeam: teams.banfield,
    awayTeam: teams.defensaYJusticia,
    scheduledDate: "2026-04-25",
    scheduledTime: "16:00",
    status: "scheduled",
    minute: null,
    homeScore: null,
    awayScore: null,
    homeGoalScorers: [],
    awayGoalScorers: [],
    tvNetworks: [{ id: "idef", name: "TNT Sports Premium" }],
  },
  {
    id: "abcdefa",
    slug: "tigre-vs-sarmiento-junin",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 10",
    subTournament: "Apertura",
    homeTeam: teams.tigre,
    awayTeam: teams.sarmiento,
    scheduledDate: "2026-04-25",
    scheduledTime: "18:30",
    status: "scheduled",
    minute: null,
    homeScore: null,
    awayScore: null,
    homeGoalScorers: [],
    awayGoalScorers: [],
    tvNetworks: [{ id: "hbdg", name: "LPF Play" }],
  },
  {
    id: "abcdefb",
    slug: "rosario-central-vs-union-de-santa-fe",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 10",
    subTournament: "Apertura",
    homeTeam: teams.rosarioCentral,
    awayTeam: teams.union,
    scheduledDate: "2026-04-26",
    scheduledTime: "20:00",
    status: "scheduled",
    minute: null,
    homeScore: null,
    awayScore: null,
    homeGoalScorers: [],
    awayGoalScorers: [],
    tvNetworks: [{ id: "cicj", name: "ESPN" }],
  },
  {
    id: "abcdefc",
    slug: "instituto-vs-platense",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 10",
    subTournament: "Apertura",
    homeTeam: teams.instituto,
    awayTeam: teams.platense,
    scheduledDate: "2026-04-26",
    scheduledTime: "15:00",
    status: "scheduled",
    minute: null,
    homeScore: null,
    awayScore: null,
    homeGoalScorers: [],
    awayGoalScorers: [],
    tvNetworks: [],
  },
];
