import type { Match } from "../types.js";
import { teams } from "./teams.js";

export const pastScores: Match[] = [
  {
    id: "egdbgff",
    slug: "estudiantes-de-la-plata-vs-central-cordoba-sde",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 8",
    subTournament: "Apertura",
    homeTeam: teams.estudiantesLP,
    awayTeam: teams.centralCordoba,
    scheduledDate: "2026-04-12",
    scheduledTime: "18:00",
    status: "finished",
    minute: null,
    homeScore: 2,
    awayScore: 0,
    homeGoalScorers: [
      { playerName: "Boselli", minute: 34, isPenalty: false, isOwnGoal: false },
      { playerName: "Rodríguez", minute: 71, isPenalty: false, isOwnGoal: false },
    ],
    awayGoalScorers: [],
    tvNetworks: [{ id: "cicj", name: "ESPN" }],
  },
  {
    id: "egdbgfg",
    slug: "boca-juniors-vs-racing-club",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 8",
    subTournament: "Apertura",
    homeTeam: teams.boca,
    awayTeam: teams.racing,
    scheduledDate: "2026-04-12",
    scheduledTime: "20:15",
    status: "finished",
    minute: null,
    homeScore: 2,
    awayScore: 1,
    homeGoalScorers: [
      { playerName: "Cavani", minute: 23, isPenalty: false, isOwnGoal: false },
      { playerName: "Cavani", minute: 67, isPenalty: true, isOwnGoal: false },
    ],
    awayGoalScorers: [
      { playerName: "Almendra", minute: 55, isPenalty: false, isOwnGoal: false },
    ],
    tvNetworks: [{ id: "gchc", name: "ESPN Premium" }],
  },
  {
    id: "egdbgfh",
    slug: "river-plate-vs-belgrano",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 8",
    subTournament: "Apertura",
    homeTeam: teams.river,
    awayTeam: teams.belgrano,
    scheduledDate: "2026-04-12",
    scheduledTime: "16:00",
    status: "finished",
    minute: null,
    homeScore: 3,
    awayScore: 0,
    homeGoalScorers: [
      { playerName: "Driussi", minute: 12, isPenalty: false, isOwnGoal: false },
      { playerName: "Driussi", minute: 56, isPenalty: false, isOwnGoal: false },
      { playerName: "Colidio", minute: 78, isPenalty: false, isOwnGoal: false },
    ],
    awayGoalScorers: [],
    tvNetworks: [{ id: "idef", name: "TNT Sports Premium" }],
  },
  {
    id: "egdbgfi",
    slug: "velez-sarsfield-vs-lanus",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 8",
    subTournament: "Apertura",
    homeTeam: teams.velez,
    awayTeam: teams.lanus,
    scheduledDate: "2026-04-11",
    scheduledTime: "19:00",
    status: "finished",
    minute: null,
    homeScore: 1,
    awayScore: 1,
    homeGoalScorers: [
      { playerName: "Janson", minute: 40, isPenalty: false, isOwnGoal: false },
    ],
    awayGoalScorers: [
      { playerName: "Sand", minute: 88, isPenalty: false, isOwnGoal: false },
    ],
    tvNetworks: [{ id: "cbcj", name: "TyC Sports" }],
  },
  {
    id: "egdbgfj",
    slug: "san-lorenzo-vs-huracan",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 8",
    subTournament: "Apertura",
    homeTeam: teams.sanLorenzo,
    awayTeam: teams.huracan,
    scheduledDate: "2026-04-11",
    scheduledTime: "21:00",
    status: "finished",
    minute: null,
    homeScore: 0,
    awayScore: 2,
    homeGoalScorers: [],
    awayGoalScorers: [
      { playerName: "Ramírez", minute: 15, isPenalty: false, isOwnGoal: false },
      { playerName: "Cóccaro", minute: 63, isPenalty: false, isOwnGoal: false },
    ],
    tvNetworks: [{ id: "gchc", name: "ESPN Premium" }],
  },
  {
    id: "egdbgfk",
    slug: "talleres-de-cordoba-vs-banfield",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 7",
    subTournament: "Apertura",
    homeTeam: teams.talleres,
    awayTeam: teams.banfield,
    scheduledDate: "2026-04-05",
    scheduledTime: "18:00",
    status: "finished",
    minute: null,
    homeScore: 3,
    awayScore: 1,
    homeGoalScorers: [
      { playerName: "Valoyes", minute: 22, isPenalty: false, isOwnGoal: false },
      { playerName: "Valoyes", minute: 51, isPenalty: false, isOwnGoal: false },
      { playerName: "Santos", minute: 85, isPenalty: false, isOwnGoal: false },
    ],
    awayGoalScorers: [
      { playerName: "Urzi", minute: 44, isPenalty: false, isOwnGoal: false },
    ],
    tvNetworks: [{ id: "cicj", name: "ESPN" }],
  },
  {
    id: "egdbgfl",
    slug: "independiente-vs-godoy-cruz",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 7",
    subTournament: "Apertura",
    homeTeam: teams.independiente,
    awayTeam: teams.godoyCruz,
    scheduledDate: "2026-04-05",
    scheduledTime: "20:15",
    status: "finished",
    minute: null,
    homeScore: 1,
    awayScore: 0,
    homeGoalScorers: [
      { playerName: "Cauteruccio", minute: 73, isPenalty: true, isOwnGoal: false },
    ],
    awayGoalScorers: [],
    tvNetworks: [{ id: "idef", name: "TNT Sports Premium" }],
  },
  {
    id: "egdbgfm",
    slug: "newells-old-boys-vs-rosario-central",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 7",
    subTournament: "Apertura",
    homeTeam: teams.newells,
    awayTeam: teams.rosarioCentral,
    scheduledDate: "2026-04-06",
    scheduledTime: "17:00",
    status: "finished",
    minute: null,
    homeScore: 2,
    awayScore: 2,
    homeGoalScorers: [
      { playerName: "Ramírez", minute: 18, isPenalty: false, isOwnGoal: false },
      { playerName: "Fernández", minute: 64, isPenalty: false, isOwnGoal: false },
    ],
    awayGoalScorers: [
      { playerName: "Vecchio", minute: 32, isPenalty: false, isOwnGoal: false },
      { playerName: "Martínez", minute: 90, isPenalty: false, isOwnGoal: false },
    ],
    tvNetworks: [{ id: "gchc", name: "ESPN Premium" }],
  },
  {
    id: "egdbgfn",
    slug: "defensa-y-justicia-vs-tigre",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 7",
    subTournament: "Apertura",
    homeTeam: teams.defensaYJusticia,
    awayTeam: teams.tigre,
    scheduledDate: "2026-04-06",
    scheduledTime: "19:00",
    status: "finished",
    minute: null,
    homeScore: 0,
    awayScore: 1,
    homeGoalScorers: [],
    awayGoalScorers: [
      { playerName: "Retegui", minute: 53, isPenalty: false, isOwnGoal: false },
    ],
    tvNetworks: [{ id: "cbcj", name: "TyC Sports" }],
  },
  {
    id: "egdbgfo",
    slug: "gimnasia-la-plata-vs-argentinos-juniors",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 8",
    subTournament: "Apertura",
    homeTeam: teams.gimnasiaLP,
    awayTeam: teams.argentinos,
    scheduledDate: "2026-04-13",
    scheduledTime: "15:30",
    status: "finished",
    minute: null,
    homeScore: 1,
    awayScore: 1,
    homeGoalScorers: [
      { playerName: "Carbonero", minute: 28, isPenalty: false, isOwnGoal: false },
    ],
    awayGoalScorers: [
      { playerName: "Ávalos", minute: 61, isPenalty: false, isOwnGoal: false },
    ],
    tvNetworks: [{ id: "hbdg", name: "LPF Play" }],
  },
  {
    id: "egdbgfp",
    slug: "platense-vs-independiente-rivadavia",
    leagueId: "hc",
    leagueName: "Liga Profesional",
    round: "Fecha 8",
    subTournament: "Apertura",
    homeTeam: teams.platense,
    awayTeam: teams.independienteRiv,
    scheduledDate: "2026-04-13",
    scheduledTime: "17:00",
    status: "finished",
    minute: null,
    homeScore: 2,
    awayScore: 0,
    homeGoalScorers: [
      { playerName: "Benavídez", minute: 37, isPenalty: false, isOwnGoal: false },
      { playerName: "Gómez", minute: 82, isPenalty: false, isOwnGoal: false },
    ],
    awayGoalScorers: [],
    tvNetworks: [{ id: "cbcj", name: "TyC Sports" }],
  },
];
