import type { LeagueTableRow } from "../types.js";
import { teams } from "./teams.js";

export const leagueTable: LeagueTableRow[] = [
  {
    position: 1,
    team: teams.boca,
    played: 8, won: 6, drawn: 1, lost: 1,
    goalsFor: 14, goalsAgainst: 5, goalDifference: 9,
    points: 19,
    zone: "libertadores",
  },
  {
    position: 2,
    team: teams.river,
    played: 8, won: 5, drawn: 2, lost: 1,
    goalsFor: 13, goalsAgainst: 4, goalDifference: 9,
    points: 17,
    zone: "libertadores",
  },
  {
    position: 3,
    team: teams.velez,
    played: 8, won: 5, drawn: 1, lost: 2,
    goalsFor: 11, goalsAgainst: 6, goalDifference: 5,
    points: 16,
    zone: "libertadores",
  },
  {
    position: 4,
    team: teams.talleres,
    played: 8, won: 5, drawn: 1, lost: 2,
    goalsFor: 12, goalsAgainst: 8, goalDifference: 4,
    points: 16,
    zone: "libertadores",
  },
  {
    position: 5,
    team: teams.estudiantesLP,
    played: 8, won: 4, drawn: 3, lost: 1,
    goalsFor: 10, goalsAgainst: 5, goalDifference: 5,
    points: 15,
    zone: "sudamericana",
  },
  {
    position: 6,
    team: teams.huracan,
    played: 8, won: 4, drawn: 2, lost: 2,
    goalsFor: 9, goalsAgainst: 6, goalDifference: 3,
    points: 14,
    zone: "sudamericana",
  },
  {
    position: 7,
    team: teams.racing,
    played: 8, won: 4, drawn: 2, lost: 2,
    goalsFor: 10, goalsAgainst: 8, goalDifference: 2,
    points: 14,
    zone: "sudamericana",
  },
  {
    position: 8,
    team: teams.independiente,
    played: 8, won: 4, drawn: 1, lost: 3,
    goalsFor: 8, goalsAgainst: 7, goalDifference: 1,
    points: 13,
    zone: "sudamericana",
  },
  {
    position: 9,
    team: teams.tigre,
    played: 8, won: 4, drawn: 1, lost: 3,
    goalsFor: 9, goalsAgainst: 9, goalDifference: 0,
    points: 13,
    zone: null,
  },
  {
    position: 10,
    team: teams.platense,
    played: 8, won: 3, drawn: 3, lost: 2,
    goalsFor: 8, goalsAgainst: 6, goalDifference: 2,
    points: 12,
    zone: null,
  },
  {
    position: 11,
    team: teams.argentinos,
    played: 8, won: 3, drawn: 3, lost: 2,
    goalsFor: 7, goalsAgainst: 6, goalDifference: 1,
    points: 12,
    zone: null,
  },
  {
    position: 12,
    team: teams.lanus,
    played: 8, won: 3, drawn: 2, lost: 3,
    goalsFor: 9, goalsAgainst: 8, goalDifference: 1,
    points: 11,
    zone: null,
  },
  {
    position: 13,
    team: teams.godoyCruz,
    played: 8, won: 3, drawn: 2, lost: 3,
    goalsFor: 7, goalsAgainst: 7, goalDifference: 0,
    points: 11,
    zone: null,
  },
  {
    position: 14,
    team: teams.newells,
    played: 8, won: 3, drawn: 2, lost: 3,
    goalsFor: 8, goalsAgainst: 9, goalDifference: -1,
    points: 11,
    zone: null,
  },
  {
    position: 15,
    team: teams.belgrano,
    played: 8, won: 3, drawn: 1, lost: 4,
    goalsFor: 7, goalsAgainst: 9, goalDifference: -2,
    points: 10,
    zone: null,
  },
  {
    position: 16,
    team: teams.sanLorenzo,
    played: 8, won: 2, drawn: 4, lost: 2,
    goalsFor: 6, goalsAgainst: 6, goalDifference: 0,
    points: 10,
    zone: null,
  },
  {
    position: 17,
    team: teams.instituto,
    played: 8, won: 2, drawn: 3, lost: 3,
    goalsFor: 5, goalsAgainst: 7, goalDifference: -2,
    points: 9,
    zone: null,
  },
  {
    position: 18,
    team: teams.rosarioCentral,
    played: 8, won: 2, drawn: 3, lost: 3,
    goalsFor: 8, goalsAgainst: 10, goalDifference: -2,
    points: 9,
    zone: null,
  },
  {
    position: 19,
    team: teams.defensaYJusticia,
    played: 8, won: 2, drawn: 3, lost: 3,
    goalsFor: 6, goalsAgainst: 8, goalDifference: -2,
    points: 9,
    zone: null,
  },
  {
    position: 20,
    team: teams.union,
    played: 8, won: 2, drawn: 3, lost: 3,
    goalsFor: 5, goalsAgainst: 8, goalDifference: -3,
    points: 9,
    zone: null,
  },
  {
    position: 21,
    team: teams.gimnasiaLP,
    played: 8, won: 2, drawn: 2, lost: 4,
    goalsFor: 6, goalsAgainst: 9, goalDifference: -3,
    points: 8,
    zone: null,
  },
  {
    position: 22,
    team: teams.banfield,
    played: 8, won: 2, drawn: 2, lost: 4,
    goalsFor: 5, goalsAgainst: 10, goalDifference: -5,
    points: 8,
    zone: null,
  },
  {
    position: 23,
    team: teams.atleticoTucuman,
    played: 8, won: 2, drawn: 1, lost: 5,
    goalsFor: 4, goalsAgainst: 10, goalDifference: -6,
    points: 7,
    zone: null,
  },
  {
    position: 24,
    team: teams.sarmiento,
    played: 8, won: 1, drawn: 4, lost: 3,
    goalsFor: 5, goalsAgainst: 8, goalDifference: -3,
    points: 7,
    zone: null,
  },
  {
    position: 25,
    team: teams.independienteRiv,
    played: 8, won: 1, drawn: 3, lost: 4,
    goalsFor: 4, goalsAgainst: 9, goalDifference: -5,
    points: 6,
    zone: "relegation",
  },
  {
    position: 26,
    team: teams.centralCordoba,
    played: 8, won: 1, drawn: 3, lost: 4,
    goalsFor: 3, goalsAgainst: 9, goalDifference: -6,
    points: 6,
    zone: "relegation",
  },
  {
    position: 27,
    team: teams.riestra,
    played: 8, won: 1, drawn: 2, lost: 5,
    goalsFor: 4, goalsAgainst: 12, goalDifference: -8,
    points: 5,
    zone: "relegation",
  },
  {
    position: 28,
    team: teams.barracas,
    played: 8, won: 0, drawn: 2, lost: 6,
    goalsFor: 3, goalsAgainst: 15, goalDifference: -12,
    points: 2,
    zone: "relegation",
  },
];
