import type { TeamRef } from "../types.js";

export const teams: Record<string, TeamRef> = {
  argentinos: {
    id: "ihb",
    name: "Argentinos Juniors",
    shortName: "Argentinos",
    slug: "argentinos-juniors",
  },
  atleticoTucuman: {
    id: "gbfc",
    name: "Atlético Tucumán",
    shortName: "Atl. Tucumán",
    slug: "atletico-tucuman",
  },
  banfield: {
    id: "ihi",
    name: "Banfield",
    shortName: "Banfield",
    slug: "banfield",
  },
  barracas: {
    id: "jafb",
    name: "Barracas Central",
    shortName: "Barracas",
    slug: "barracas-central",
  },
  belgrano: {
    id: "fhid",
    name: "Belgrano",
    shortName: "Belgrano",
    slug: "belgrano",
  },
  boca: {
    id: "igg",
    name: "Boca Juniors",
    shortName: "Boca",
    slug: "boca-juniors",
  },
  centralCordoba: {
    id: "beafh",
    name: "Central Córdoba SdE",
    shortName: "C. Córdoba",
    slug: "central-cordoba-sde",
  },
  defensaYJusticia: {
    id: "hcbh",
    name: "Defensa y Justicia",
    shortName: "Def. y Just.",
    slug: "defensa-y-justicia",
  },
  riestra: {
    id: "bbjea",
    name: "Deportivo Riestra",
    shortName: "Riestra",
    slug: "deportivo-riestra",
  },
  estudiantesLP: {
    id: "igh",
    name: "Estudiantes de La Plata",
    shortName: "Estudiantes",
    slug: "estudiantes-de-la-plata",
  },
  gimnasiaLP: {
    id: "iia",
    name: "Gimnasia y Esgrima La Plata",
    shortName: "Gimnasia",
    slug: "gimnasia-la-plata",
  },
  godoyCruz: {
    id: "ihd",
    name: "Godoy Cruz",
    shortName: "Godoy Cruz",
    slug: "godoy-cruz",
  },
  huracan: {
    id: "iie",
    name: "Huracán",
    shortName: "Huracán",
    slug: "huracan",
  },
  independiente: {
    id: "ihe",
    name: "Independiente",
    shortName: "Independiente",
    slug: "independiente",
  },
  independienteRiv: {
    id: "hcch",
    name: "Independiente Rivadavia",
    shortName: "Ind. Rivadavia",
    slug: "independiente-rivadavia",
  },
  instituto: {
    id: "hchc",
    name: "Instituto",
    shortName: "Instituto",
    slug: "instituto",
  },
  lanus: {
    id: "igj",
    name: "Lanús",
    shortName: "Lanús",
    slug: "lanus",
  },
  newells: {
    id: "ihh",
    name: "Newell's Old Boys",
    shortName: "Newell's",
    slug: "newells-old-boys",
  },
  platense: {
    id: "hcah",
    name: "Platense",
    shortName: "Platense",
    slug: "platense",
  },
  racing: {
    id: "ihg",
    name: "Racing Club",
    shortName: "Racing",
    slug: "racing-club",
  },
  river: {
    id: "igi",
    name: "River Plate",
    shortName: "River",
    slug: "river-plate",
  },
  rosarioCentral: {
    id: "ihf",
    name: "Rosario Central",
    shortName: "R. Central",
    slug: "rosario-central",
  },
  sanLorenzo: {
    id: "igf",
    name: "San Lorenzo",
    shortName: "San Lorenzo",
    slug: "san-lorenzo",
  },
  sarmiento: {
    id: "hbbh",
    name: "Sarmiento de Junín",
    shortName: "Sarmiento",
    slug: "sarmiento-junin",
  },
  talleres: {
    id: "jche",
    name: "Talleres de Córdoba",
    shortName: "Talleres",
    slug: "talleres-de-cordoba",
  },
  tigre: {
    id: "iid",
    name: "Tigre",
    shortName: "Tigre",
    slug: "tigre",
  },
  union: {
    id: "hcag",
    name: "Unión de Santa Fe",
    shortName: "Unión",
    slug: "union-de-santa-fe",
  },
  velez: {
    id: "ihc",
    name: "Vélez Sarsfield",
    shortName: "Vélez",
    slug: "velez-sarsfield",
  },
};
